---
driver:
  name: vagrant
  memory: 1024
  network:
  - ["forwarded_port", {guest: 6311, host: 6311, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.9
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[iptables]
      - recipe[RServe::add_epel]
      - recipe[RServe::install_r]
      - recipe[RServe::install_rserve]
      - recipe[RServe::create_rserve_service]
      - recipe[RServe::create_credentials]
      - recipe[RServe::rserved_service]
      - recipe[RServe::iptables_rule]
    attributes: {}
    data_path: installation_data
    data_bags_path: './test/integration/default/data_bags/'
    encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'
