---
driver:
  name: vagrant
  memory: 1024
  network:
  - ["forwarded_port", {guest: 6311, host: 6311, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7-vbox
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
      provider: virtualbox
  - name: centos-6.7-vmware
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
      provider: vmware_fusion
  - name:  ubuntu-trusty-vbox
    driver:
      box: ubuntu/trusty64
      box_url: ubuntu/trusty64
      provider: virtualbox

suites:
  - name: default
    run_list:
      - recipe[iptables]
      - recipe[RServe]
    attributes: {}
    data_path: installation_data
    data_bags_path: './test/integration/default/data_bags/'
    encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'